package linux

import "testing"

const chronyFixture = `# Managed by configuration management
pool 2.debian.pool.ntp.org iburst
server ntp1.internal.example.sa iburst prefer
#server disabled.example.com iburst
! also a comment in chrony syntax
driftfile /var/lib/chrony/chrony.drift
makestep 1.0 3
`

func TestParseChrony(t *testing.T) {
	got := ParseChrony(chronyFixture)

	if !got.Configured {
		t.Fatal("time sources present but Configured is false")
	}
	if len(got.Sources) != 2 {
		t.Fatalf("sources = %v, want 2 (commented directives must be skipped)", got.Sources)
	}
	if got.Sources[1] != "ntp1.internal.example.sa" {
		t.Errorf("second source = %q; options after the host must be stripped", got.Sources[1])
	}
	// '!' is a chrony comment character; treating it as a directive would
	// invent a time source that does not exist.
	for _, s := range got.Sources {
		if s == "also" {
			t.Error("'!' comment line was parsed as a directive")
		}
	}
}

func TestParseChronyEmpty(t *testing.T) {
	if got := ParseChrony("# only comments\n"); got.Configured {
		t.Error("a file with no directives must report Configured=false")
	}
}

const timesyncdFixture = `[Time]
#NTP=
NTP=ntp1.internal.example.sa ntp2.internal.example.sa
FallbackNTP=pool.ntp.org
`

func TestParseTimesyncd(t *testing.T) {
	got := ParseTimesyncd(timesyncdFixture)

	// Unlike chrony, timesyncd puts several servers on one line — parsing only
	// the first would under-report the configuration.
	if len(got.Sources) != 3 {
		t.Fatalf("sources = %v, want 3 (two NTP plus one fallback)", got.Sources)
	}
	if got.Sources[0] != "ntp1.internal.example.sa" || got.Sources[1] != "ntp2.internal.example.sa" {
		t.Errorf("space-separated servers not split correctly: %v", got.Sources)
	}
}

const resolvFixture = `# Generated by NetworkManager
nameserver 10.200.157.1
nameserver 8.8.8.8
#nameserver 1.1.1.1
search example.sa
options edns0
`

func TestParseResolvConf(t *testing.T) {
	got := ParseResolvConf(resolvFixture)

	if len(got) != 2 {
		t.Fatalf("nameservers = %v, want 2 (commented entries excluded)", got)
	}
	if got[0] != "10.200.157.1" || got[1] != "8.8.8.8" {
		t.Errorf("nameservers = %v", got)
	}
	if _, isPublic := PublicResolvers[got[0]]; isPublic {
		t.Error("10.200.157.1 must not be classified as a public resolver")
	}
	if op, isPublic := PublicResolvers[got[1]]; !isPublic || op != "Google" {
		t.Error("8.8.8.8 must be identified as Google public DNS")
	}
}

func TestIsLoopbackResolver(t *testing.T) {
	// A local stub resolver forwards upstream, so it is neither public nor
	// evidence of an entity-controlled resolver. It must be distinguishable.
	for _, addr := range []string{"127.0.0.1", "127.0.0.53", "::1"} {
		if !IsLoopbackResolver(addr) {
			t.Errorf("%s should be recognised as a loopback stub resolver", addr)
		}
	}
	for _, addr := range []string{"10.200.157.1", "8.8.8.8"} {
		if IsLoopbackResolver(addr) {
			t.Errorf("%s is not a loopback resolver", addr)
		}
	}
}
